version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go -b 0.0.0.0
    depends_on:
      - database
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin 
      MYSQL_DATABASE: mapi
      MYSQL_USER: mapi
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
