version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: go run cmd/server/main.go -b 0.0.0.0
  processor:
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: go run cmd/processor/main.go -b 0.0.0.0
